// <auto-generated />
namespace FP.Cloud.OnlineRateTable.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RateTableFiles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RateTableFiles));
        
        string IMigrationMetadata.Id
        {
            get { return "201510130628386_RateTableFiles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
